### PR TITLE
Implement gen_rand_id execution

### PR DESCRIPTION
**Pull request by CohenArthur**
Needs #26

### CODE REVIEW

**Review by Skallwar — APPROVED** [review]
This need to be rebase on top of master before merging, no ?

**Comment by CohenArthur** [comment]
Yes, it needs #27 to be merged first since we use `mem_write()`. I should keep it as a draft for now

**Review by CohenArthur — COMMENTED** [review]
LGTM!

**Review by CohenArthur — COMMENTED** [review]
Great, I agree that we shouldn't use *answer for storing and displaying the ID so I like the idea of a second buffer. Good job!

**Pull request merged**
